Repository 100-hours-a-week/15-Leafresh-FE, pull requests merged in 2025-07, with the labels that each got.

#308 PR:[fix] middleware maintenance 강제 이동 조건 변경
  src/middleware.ts
Labels: feat

#311 PR:[fix] KST 변환 중간 과정 추가
  src/features/challenge/components/challenge-participant-card/challenge-participant-card.tsx
  src/widgets/member/challenge/participate/list/member-challenge-participate-list.tsx
Labels: bug

#317 PR:[feat] prod, dev 프로메테우스 모니터링 적용
  package.json
  pnpm-lock.yaml
  src/app/api/metrics/route.ts
  src/app/api/metrics/scripts/metrics-server.ts
  src/middleware.ts
  src/shared/lib/api/utils.ts
Labels: infra, FE, CL

#318 PR[fix]: dev proxy route 수정
  src/app/api/proxy/[...path]/route.ts
Labels: bug, FE

#326 FE (PR) feat: 썸네일 이미지 업로드 방식 촬영 -> 파일 업로드로 변경
  src/features/challenge/components/form-detail-step/form-detail-step.tsx
  src/features/challenge/components/form-detail-step/thumbnail-image-input.tsx
  src/shared/components/modal/camera-modal/camera-modal.tsx
  src/shared/hooks/index.ts
  src/shared/hooks/use-image-uplaod/index.ts
  src/shared/hooks/use-process-image-file/index.ts
  src/shared/hooks/use-process-image-file/use-process-image-file.ts
  src/shared/hooks/use-upload-image-to-bucket/index.ts
  src/shared/hooks/use-upload-image-to-bucket/useUploadImageToBucket.ts
  src/widgets/member/profile/modify/member-profile-modify.tsx
Labels: feat, FE

#328 feat: metrics-server.js 실행 추가 및 Dockerfile CMD 수정
  Dockerfile
  scripts/metrics-server.js
Labels: feat, FE, CL

#329 PR FE (feat) : V2 배포 전 QA 및 에러상황 핸들링
  src/entities/member/api/store/get-leaf-count.ts
  src/entities/member/api/store/index.ts
  src/features/challenge/components/(deprectaed-list)group-challenge-card/(deprectaed-list)group-challenge-card.tsx
  src/features/member/components/profile-card/profile-card.tsx
  src/features/store/components/ongoing-timedeal-card/ongoing-timedeal-card.tsx
  src/features/store/components/ongoing-timedeal-list/ongoing-timedeal-list.tsx
  src/features/store/components/product-card/product-card.tsx
  src/features/store/components/product-list/product-list.tsx
  src/features/store/components/timedeal-list/timedeal-list.tsx
  src/features/store/components/upcoming-timedeal-list/upcoming-timedeal-list.tsx
  src/shared/components/introduce/introduce.tsx
  src/shared/lib/date/utils.ts
  src/widgets/challenge/group/[id]/details/challenge-group-details.tsx
  src/widgets/challenge/personal/[id]/details/challenge-personal-details.tsx
  src/widgets/member/store/list/member-store-order-list.tsx
  src/widgets/store/main/store.tsx
Labels: bug, FE

#331 PR FE (fix) : 과거 토큰 삭제 API Route 추가
  src/app/(with-layout)/layout.tsx
  src/app/api/cleanup-token/route.ts
  src/features/common/components/index.ts
  src/features/common/components/token-deleter/index.ts
  src/features/common/components/token-deleter/token-deleter.tsx
Labels: bug, FE

#334 PR FE (bug/chore) : 이미지 비율 불일치 현상 해결 및 모바일 환경의 video 크기 조정
  src/features/challenge/components/form-detail-step/thumbnail-image-input.tsx
  src/features/challenge/components/group-challenge-card/group-challenge-card.tsx
  src/features/challenge/components/verification-card/verification-card.tsx
  src/features/main/components/event-section/event-section.tsx
  src/features/main/components/personal-challenge-section/personal-challenge-section.tsx
  src/shared/components/modal/camera-modal/camera-modal.tsx
  src/shared/constants/image-size.ts
  src/widgets/challenge/group/[id]/details/challenge-group-details.tsx
  src/widgets/challenge/group/[id]/verification/details/challenge-group-verification-details.tsx
  src/widgets/challenge/group/feed/challenge-group-feed.tsx
  src/widgets/challenge/personal/[id]/details/challenge-personal-details.tsx
Labels: feat, bug, FE

#343 PR FE (fix) : 나뭇잎 상점 개수 낙관적 업데이트 및 개수 예외 처리
  src/features/main/components/personal-challenge-section/personal-challenge-section.tsx
  src/features/store/components/ongoing-timedeal-card/ongoing-timedeal-card.tsx
  src/features/store/components/ongoing-timedeal-list/ongoing-timedeal-list.tsx
  src/features/store/components/product-card/product-card.tsx
  src/features/store/components/product-list/product-list.tsx
Labels: bug, FE

#347 feat: prod ci/cd 반영 및 PR 푸시 단위로 변경
  .github/workflows/fe-cicd.yml
Labels: feat, FE, CL

#355 PR FE (fix): QA 핸들링 및 카메로 모달 헤더 크기 고정 (크로스 브라우징)
  src/shared/components/introduce/introduce.tsx
  src/shared/components/introduce/styles.ts
  src/shared/components/modal/camera-modal/styles.ts
  src/shared/components/switchtap/switch-tab.tsx
  src/widgets/main/main.tsx
  src/widgets/member/alarm/list/member-alarm-list.tsx
  src/widgets/member/alarm/list/styles.ts
Labels: bug, chore, style, FE

#359 PR FE (fix) : 크로스 브라우징 스타일 에러 해결
  src/features/main/components/group-challenge-section/styles.ts
  src/features/store/components/product-card/product-card.tsx
  src/features/store/components/product-card/styles.ts
  src/widgets/challenge/group/feed/styles.ts
  src/widgets/member/profile/modify/styles.ts
Labels: bug, style, FE

#360 V2.0.0 릴리즈
  src/features/main/components/group-challenge-section/styles.ts
  src/features/store/components/product-card/product-card.tsx
  src/features/store/components/product-card/styles.ts
  src/middleware.ts
  src/shared/components/introduce/introduce.tsx
  src/shared/components/introduce/styles.ts
  src/shared/components/modal/camera-modal/camera-modal.tsx
  src/shared/components/modal/camera-modal/styles.ts
  src/shared/components/switchtap/switch-tab.tsx
  src/shared/constants/image-size.ts
  src/widgets/challenge/group/feed/styles.ts
  src/widgets/main/main.tsx
  src/widgets/member/alarm/list/member-alarm-list.tsx
  src/widgets/member/alarm/list/styles.ts
  src/widgets/member/profile/modify/styles.ts
Labels: feat, FE

#378 PR FE (fix) : SSR 이후 CSR에서 불필요한 refetch 제거
  src/app/(with-layout)/(with-header)/page.tsx
  src/shared/config/tanstack-query/query-client.ts
  src/shared/config/tanstack-query/query-defaults.ts
  src/widgets/challenge/group/[id]/verification/details/challenge-group-verification-details.tsx
Labels: bug, FE

#376 PR FE (feat) : 단체 챌린지 참여 후, "인증 대기"로 라우팅 되도록 변경
  src/app/(with-layout)/(with-header)/member/challenge/participate/list/page.tsx
  src/shared/components/navbar/consts.ts
  src/shared/constants/route.ts
  src/shared/lib/utils/build-uri.ts
  src/shared/lib/utils/index.ts
  src/widgets/challenge/group/[id]/details/challenge-group-details.tsx
  src/widgets/member/challenge/participate/list/member-challenge-participate-list.tsx
  src/widgets/member/challenge/verification/status/member-challenge-verification-status.tsx
Labels: feat, FE

#382 fix: prod ci/cd 변경 및 Dockerfile 명시적 파일 복사
  .github/workflows/fe-cicd.yml
  Dockerfile
Labels: refactor, FE, CL

#402 PR FE (fix): 피드 리스트 무한스크롤 옵저버 해제
  src/features/challenge/components/feed-list/feed-list.tsx
Labels: bug, FE

#404 PR FE (bug): 순환참조 디버깅
  eslint.config.mjs
  src/app/(with-layout)/(with-header)/member/alarm/page.tsx
  src/app/(with-layout)/(with-header)/member/challenge/participate/list/page.tsx
  src/entities/challenge/api/alarm/get-alarm-list.ts
  src/entities/challenge/api/alarm/index.ts
  src/entities/challenge/api/alarm/read-alarm-list.ts
  src/entities/challenge/api/index.ts
  src/entities/chatbot/model/type.ts
  src/entities/member/api/challenge/index.ts
  src/features/challenge/components/index.ts
  src/features/challenge/components/modal/camera-modal/camera-modal.tsx
  src/features/challenge/components/modal/camera-modal/index.ts
  src/features/challenge/components/modal/camera-modal/styles.ts
  src/features/challenge/components/modal/image-zoom-modal/image-zoom-modal.tsx
  src/features/challenge/components/modal/image-zoom-modal/index.ts
  src/features/challenge/components/modal/image-zoom-modal/styles.ts
  src/features/challenge/components/modal/index.ts
  src/features/challenge/components/modal/verification-guide-modal/index.ts
  src/features/challenge/components/modal/verification-guide-modal/styles.ts
  src/features/challenge/components/modal/verification-guide-modal/verification-guide-modal.tsx
  src/features/chatbot/api/use-chat-history.ts
  src/features/member/api/alarm/use-get-alarm-list.ts
  src/shared/components/modal/index.ts
  src/shared/config/providers/modal-provider.tsx
  src/shared/config/tanstack-query/mutation-defaults.ts
  src/widgets/member/alarm/list/member-alarm-list.tsx
Labels: bug, FE

#399 FE PR (feat) : 인증/인가 로직 클라이언트 -> 서버 마이그레이션
  src/app/(with-layout)/(with-header)/member/login/page.tsx
  src/app/(with-layout)/layout.tsx
  src/features/challenge/components/challenge-create-button/challenge-create-button.tsx
  src/features/challenge/components/group-challenge-card/group-challenge-card.tsx
  src/features/challenge/components/verification-card/verification-card.tsx
  src/features/store/components/ongoing-timedeal-card/ongoing-timedeal-card.tsx
  src/features/store/components/ongoing-timedeal-list/ongoing-timedeal-list.tsx
  src/features/store/components/product-card/product-card.tsx
  src/middleware.ts
  src/shared/components/header/header.tsx
  src/shared/config/providers/auth-gaurd.tsx
  src/shared/config/providers/index.ts
  src/shared/constants/route.ts
  src/shared/lib/api/error-handler/handle-auth-error.ts
  src/shared/lib/api/server-fetcher/server-fetcher.ts
  src/shared/lib/api/server-fetcher/server-reissue.ts
  src/shared/lib/api/utils.ts
  src/shared/lib/index.ts
  src/shared/lib/middleware/auth_gaurd.ts
  src/shared/lib/middleware/check_maintenance.ts
  src/shared/lib/middleware/index.ts
  src/shared/lib/middleware/is_token_valid.ts
  src/widgets/challenge/group/[id]/details/challenge-group-details.tsx
  src/widgets/challenge/group/[id]/verification/details/challenge-group-verification-details.tsx
  src/widgets/challenge/personal/[id]/details/challenge-personal-details.tsx
  src/widgets/member/challenge/verification/status/member-challenge-verification-status.tsx
  src/widgets/member/login/login.tsx
  src/widgets/member/oauth-callback/callback.tsx
Labels: feat, FE

#417 fix: 나뭇잎 개수가 0개인 경우에도 정상적 렌더링 표시
  src/features/store/components/ongoing-timedeal-list/ongoing-timedeal-list.tsx
Labels: bug, FE

#416 PR (FE) fix: 단체 챌린지 인증 버튼 / 라벨 동기화
  src/entities/challenge/api/group/get-group-details.ts
  src/widgets/challenge/group/[id]/details/challenge-group-details.tsx
Labels: feat, bug, FE

#426 PR (FE) epic: QA 및 에러 핸들링
  src/app/(with-layout)/(with-header)/challenge/group/create/page.tsx
  src/features/challenge/components/modal/camera-modal/camera-modal.tsx
  src/features/challenge/components/modal/camera-modal/styles.ts
  src/features/challenge/components/modal/camera-modal/types.ts
  src/features/challenge/components/verification-card/styles.ts
  src/features/challenge/components/verification-card/verification-card.tsx
  src/features/main/components/introduce/introduce.tsx
  src/features/main/components/introduce/styles.ts
  src/widgets/challenge/group/[id]/verification/details/challenge-group-verification-details.tsx
  src/widgets/challenge/group/[id]/verification/details/styles.ts
  src/widgets/challenge/personal/[id]/details/challenge-personal-details.tsx
  src/widgets/member/login/styles.ts
Labels: feat, bug, style, FE

#434 프론트엔드(DEV)용 Helm 차트 추가
  helm/frontend/.helmignore
  helm/frontend/Chart.yaml
  helm/frontend/templates/_helpers.tpl
  helm/frontend/templates/deployment.yaml
  helm/frontend/templates/hpa.yaml
  helm/frontend/templates/ingress.yaml
  helm/frontend/templates/service.yaml
  helm/frontend/templates/serviceaccount.yaml
  helm/frontend/values.yaml
  scripts/metrics-server.ts
Labels: FE, CL

#436 fix: 캘린더 월 변경 버튼 클릭 시 폼 트리거 버그
  src/features/challenge/components/modal/camera-modal/camera-modal.tsx
  src/shared/components/calender/header/calender-header.tsx
Labels: bug, FE

#437 Prod CI/CD, 캘린더 월 변경 에러
  .github/workflows/fe-cicd.yml
  Dockerfile
  helm/frontend/.helmignore
  helm/frontend/Chart.yaml
  helm/frontend/templates/_helpers.tpl
  helm/frontend/templates/deployment.yaml
  helm/frontend/templates/hpa.yaml
  helm/frontend/templates/ingress.yaml
  helm/frontend/templates/service.yaml
  helm/frontend/templates/serviceaccount.yaml
  helm/frontend/values.yaml
  scripts/metrics-server.ts
  src/features/challenge/components/modal/camera-modal/camera-modal.tsx
  src/shared/components/calender/header/calender-header.tsx
  src/shared/lib/api/utils.ts
Labels: FE

#438 FE (PR) feat: S3 이미지 업로드
  next.config.ts
Labels: feat, FE

#255 RP:[feat] 챗봇 폴링 -> SSE 변경
  next.config.ts
  pnpm-lock.yaml
  src/entities/chatbot/model/constants.ts
  src/entities/chatbot/model/index.ts
  src/entities/chatbot/model/utils.ts
  src/features/chatbot/api/index.ts
  src/features/chatbot/api/stream-api.ts
  src/features/chatbot/api/use-chat-history.ts
  src/features/chatbot/api/use-chatbot-sse.ts
  src/features/chatbot/api/use-stream-api.ts
  src/features/chatbot/components/chat-bubble/chat-bubble.tsx
  src/features/chatbot/components/chat-bubble/styles.ts
  src/features/chatbot/components/chat-frame-api/chat-frame-api.tsx
  src/features/chatbot/components/chat-frame-api/index.ts
  src/features/chatbot/components/chat-frame-api/styles.ts
  src/features/chatbot/components/chat-frame/chat-frame.tsx
  src/features/chatbot/components/chat-header/chat-header.tsx
  src/features/chatbot/components/chat-selection/chat-selection.tsx
  src/features/chatbot/components/chat-selection/styles.ts
  src/features/chatbot/components/chat-window/chat-window.tsx
  src/features/chatbot/components/chatbot/chatbot.tsx
  src/features/chatbot/components/horizontal-card/horizontal-card.tsx
  src/features/chatbot/components/horizontal-card/index.ts
  src/features/chatbot/components/index.ts
  src/shared/components/slidearea/slide-area.tsx
  src/shared/constants/image-bucket.ts
  src/shared/constants/index.ts
  src/widgets/challenge/group/[id]/verification/details/challenge-group-verification-details.tsx
  src/widgets/challenge/group/form/challenge-form.tsx
Labels: feat, FE

#447 PR[style]: 로그인 버튼 스타일 수정
  src/widgets/member/login/styles.ts
Labels: style, FE

#451 fix: 재수정 - 개인 챌린지 UTC 표시 / 카메라 촬영 후 좌우 반전 오류
  src/features/challenge/components/modal/camera-modal/camera-modal.tsx
  src/features/challenge/components/modal/camera-modal/styles.ts
  src/shared/lib/date/utils.ts
Labels: bug, FE
