Repository 100-hours-a-week/15-Leafresh-FE, pull requests merged in 2025-06, with the labels that each got.

#171 PR:[feat] 나의 활동 뱃지 조회 페이지
  src/app/(with-header)/member/profile/badge/page.tsx
  src/entities/member/constant.ts
  src/features/member/api/profile/get-badge.ts
  src/features/member/api/profile/get-member-feedback.ts
  src/features/member/api/profile/get-member-profile.ts
  src/features/member/api/profile/get-member-profilecard.ts
  src/features/member/api/profile/get-recent-badge.ts
  src/features/member/api/profile/post-member-feedback.ts
  src/features/member/components/member/profile/badge/BadgeTab.tsx
  src/features/member/components/member/profile/badge/index.tsx
  src/shared/config/tanstack-query/query-defaults.ts
  src/shared/config/tanstack-query/query-keys.ts
  src/shared/constants/route/route.ts
Labels: feat, FE

#177 PR: [feat] 메인화면 변경 및 레이아웃 고정
  .vscode/json.code-snippets
  public/icon/leaf.svg
  public/image/chatbot/chatbot.svg
  src/app/(with-header)/MainPage.tsx
  src/app/(with-header)/challenge/ChallengeMainPage.tsx
  src/app/(with-header)/challenge/page.tsx
  src/app/(with-header)/challenge/personal/[id]/ChallengePersonalDetails.tsx
  src/app/(with-header)/fe-oauth/[provider]/login/page.tsx
  src/app/(with-header)/layout.tsx
  src/app/(with-header)/member/signup/page.tsx
  src/app/(with-header)/page.tsx
  src/app/layout.tsx
  src/features/challenge/api/get-group-challenge-list.ts
  src/features/challenge/components/challenge/ChallengeCreateButton.tsx
  src/features/challenge/components/challenge/group/GroupChallengeFormPage.tsx
  src/features/challenge/components/challenge/group/details/ChallengeGroupDetails.tsx
  src/features/challenge/components/challenge/group/list/ChallengeListPage.tsx
  src/features/challenge/components/challenge/participate/ChallengeParticipatePage.tsx
  src/features/challenge/components/challenge/participate/GroupChallengeParticipantCard.tsx
  src/features/challenge/components/challenge/participate/GroupChallengeParticipantCardList.tsx
  src/features/challenge/components/challenge/participate/GroupVerificationPage.tsx
  src/features/challenge/components/challenge/participate/list/ChallengeGroupParticipateList.tsx
  src/features/challenge/components/common/group-challenge-card/GroupChallengeCard.tsx
  src/features/challenge/components/member/alarm/MemberAlramList.tsx
  src/features/main/ChallengeImageSlider.tsx
  src/features/main/CumulativeInfo.tsx
  src/features/main/HomePage.tsx
  src/features/main/components/index.ts
  src/features/main/components/sections/event-section.tsx
  src/features/main/components/sections/group-challenge-section.tsx
  src/features/main/components/sections/index.ts
  src/features/main/components/sections/personal-challenge-section.tsx
  src/features/member/api/challenge/get-group-creations.ts
  src/features/member/components/challenge/creations/MemberChallengeCreationsPage.tsx
  src/features/member/components/store/order-list-page.tsx
  src/shared/components/chatbot/Chatbot.tsx
  src/shared/components/footer/index.tsx
  src/shared/components/header/index.tsx
  src/shared/components/index.ts
  src/shared/components/leaf-reward/index.ts
  src/shared/components/leaf-reward/reward.tsx
  src/shared/components/loading/index.tsx
  src/shared/components/navbar/index.ts
  src/shared/components/navbar/navbar.tsx
  src/shared/components/navbar/tabs.ts
  src/shared/components/no-content/no-content.tsx
  src/shared/components/slide-drawer/SlideDrawer.tsx
  src/shared/components/switchtap/SwitchTap.tsx
  src/shared/constants/route/route.ts
  src/shared/context/slide-drawer/DrawerStore.ts
  src/shared/styles/LayoutWrapper.tsx
  src/shared/styles/ResponsiveStyle.tsx
Labels: feat, style, FE

#191 Fix : CI/CD 및 태깅 테스트
  src/app/(with-header)/member/alarm/page.tsx
  src/features/member/components/challenge/creations/MemberChallengeCreationsPage.tsx
Labels: bug

#192 Update: build 단계 if 조건 변경
  .github/workflows/fe-cicd.yml
Labels: infra, FE

#182 PR: [feat] 나뭇잎 상점 페이지
  package.json
  pnpm-lock.yaml
  public/image/apologize_character.svg
  src/app/(with-header)/store/page.tsx
  src/app/layout.tsx
  src/features/store/StorePage.tsx
  src/features/store/api/get-products.ts
  src/features/store/api/get-timedeals.ts
  src/features/store/api/order-proudcts.ts
  src/features/store/api/order-timedeal.ts
  src/features/store/components/product/ProductCard.tsx
  src/features/store/components/product/ProductList.tsx
  src/features/store/components/time-deal/OngoingTimeDealCard.tsx
  src/features/store/components/time-deal/TimeDealList.tsx
  src/features/store/components/time-deal/UpcomingTimeDealCard.tsx
  src/features/store/hook/useInfiniteProducts.ts
  src/shared/components/apologize/apologize.tsx
  src/shared/config/tanstack-query/mutation-defaults.ts
  src/shared/config/tanstack-query/mutation-keys.ts
  src/shared/config/tanstack-query/query-defaults.ts
  src/shared/config/tanstack-query/query-keys.ts
  src/shared/lib/date/utils.ts
Labels: feat, FE

#202 FE: PR(feat) 404 페이지
  public/image/404.svg
  src/app/(with-header)/challenge/participate/page.tsx
  src/app/(with-layout)/(with-header)/MainPage.tsx
  src/app/(with-layout)/(with-header)/challenge/group/[id]/modify/page.tsx
  src/app/(with-layout)/(with-header)/challenge/group/[id]/page.tsx
  src/app/(with-layout)/(with-header)/challenge/group/[id]/participate/list/page.tsx
  src/app/(with-layout)/(with-header)/challenge/group/create/page.tsx
  src/app/(with-layout)/(with-header)/challenge/group/feed/FeedPage.tsx
  src/app/(with-layout)/(with-header)/challenge/group/feed/page.tsx
  src/app/(with-layout)/(with-header)/challenge/group/list/page.tsx
  src/app/(with-layout)/(with-header)/challenge/group/page.tsx
  src/app/(with-layout)/(with-header)/challenge/participate/[participateId]/page.tsx
  src/app/(with-layout)/(with-header)/challenge/participate/page.tsx
  src/app/(with-layout)/(with-header)/challenge/personal/[id]/ChallengePersonalDetails.tsx
  src/app/(with-layout)/(with-header)/challenge/personal/[id]/page.tsx
  src/app/(with-layout)/(with-header)/fe-oauth/[provider]/login/page.tsx
  src/app/(with-layout)/(with-header)/layout.tsx
  src/app/(with-layout)/(with-header)/member/alarm/page.tsx
  src/app/(with-layout)/(with-header)/member/challenges/page.tsx
  src/app/(with-layout)/(with-header)/member/login/page.tsx
  src/app/(with-layout)/(with-header)/member/profile/badge/page.tsx
  src/app/(with-layout)/(with-header)/member/profile/modify/page.tsx
  src/app/(with-layout)/(with-header)/member/profile/mypage/page.tsx
  src/app/(with-layout)/(with-header)/member/signup/page.tsx
  src/app/(with-layout)/(with-header)/member/store/list/page.tsx
  src/app/(with-layout)/(with-header)/page.tsx
  src/app/(with-layout)/(with-header)/store/page.tsx
  src/app/(with-layout)/layout.tsx
  src/app/layout.tsx
  src/app/not-found.tsx
Labels: feat, FE

#213 PR:[feat] 인증 상세 페이지
  public/icon/like.svg
  public/icon/unLike.svg
  src/app/(with-layout)/(with-header)/challenge/group/[id]/verification/[verificationId]/page.tsx
  src/app/(with-layout)/(with-header)/challenge/group/[id]/verification/list/page.tsx
  src/app/(with-layout)/(with-header)/challenge/personal/[id]/ChallengePersonalDetails.tsx
  src/entities/challenge/constant.ts
  src/entities/challenge/type.ts
  src/features/challenge/api/participate/verification/delete-verification-comment.ts
  src/features/challenge/api/participate/verification/get-verification-comment-list.ts
  src/features/challenge/api/participate/verification/get-verifycation-details.ts
  src/features/challenge/api/participate/verification/post-verification-comment.ts
  src/features/challenge/api/participate/verification/post-verification-reply.ts
  src/features/challenge/api/participate/verification/put-verification-comment.ts
  src/features/challenge/components/challenge/group/details/ChallengeGroupDetails.tsx
  src/features/challenge/components/challenge/participate/verification/details/VerificationDetails.tsx
  src/features/challenge/components/challenge/participate/verification/details/comment-item.tsx
  src/features/challenge/components/challenge/participate/verification/details/comment-list.tsx
  src/features/challenge/components/challenge/participate/verification/verification-card.tsx
  src/shared/config/tanstack-query/mutation-defaults.ts
  src/shared/config/tanstack-query/mutation-keys.ts
  src/shared/config/tanstack-query/query-defaults.ts
  src/shared/config/tanstack-query/query-keys.ts
  src/shared/constants/endpoint/endpoint.ts
  src/shared/constants/route/route.ts
  src/shared/lib/date/utils.ts
Labels: feat, FE

#227 FE: (PR) feat API 연결 및 QA
  Dockerfile
  src/app/(with-layout)/(with-header)/MainPage.tsx
  src/app/(with-layout)/(with-header)/member/[provider]/callback/CallbackPage.tsx
  src/app/(with-layout)/(with-header)/member/signup/page.tsx
  src/app/(with-layout)/(with-header)/store/page.tsx
  src/features/challenge/api/get-group-challenge-categories.ts
  src/features/challenge/api/get-group-challenge-list.ts
  src/features/challenge/api/participate/get-group-participant-list.ts
  src/features/challenge/api/participate/verification/get-verifycation-details.ts
  src/features/challenge/components/challenge/group/feed/FeedList.tsx
  src/features/challenge/components/challenge/participate/ChallengeParticipatePage.tsx
  src/features/challenge/components/challenge/participate/GroupChallengeParticipantCard.tsx
  src/features/challenge/components/challenge/participate/GroupVerificationPage.tsx
  src/features/challenge/components/challenge/participate/list/ChallengeGroupParticipateList.tsx
  src/features/challenge/components/challenge/participate/verification/details/VerificationDetails.tsx
  src/features/challenge/components/challenge/participate/verification/verification-card.tsx
  src/features/main/components/sections/group-challenge-section.tsx
  src/features/member/components/member/profile/mypage/Mypage.tsx
  src/features/store/components/product/ProductCard.tsx
  src/features/store/components/product/ProductList.tsx
  src/features/store/hook/useInfiniteProducts.ts
  src/shared/components/modal/camera-modal/CameraModal.tsx
  src/shared/constants/endpoint/endpoint.ts
  src/shared/constants/route/route.ts
  src/shared/lib/api/client-fetcher/client-fetcher.ts
  src/shared/lib/api/client-fetcher/client-reissue.ts
  src/shared/lib/api/fetcher/fetcher.ts
  src/shared/lib/api/server-fetcher/server-fetcher.ts
  src/shared/lib/api/server-fetcher/server-reissue.ts
Labels: feat, bug, style, FE

#230 fix: 상품 주문 엔드포인트 변경
  src/app/(with-layout)/(with-header)/layout.tsx
  src/features/challenge/components/member/alarm/MemberAlramList.tsx
  src/features/store/api/order-proudcts.ts
  src/features/store/components/product/ProductCard.tsx
  src/shared/constants/endpoint/endpoint.ts
Labels: bug, FE

#234 FE (PR) feat: 내부 IP 통신 API Route 설정
  .github/ISSUE_TEMPLATE/이슈-템플릿.md
  .github/pull_request_template.md
  src/app/api/proxy/[...path]/route.ts
  src/shared/constants/api-url.ts
  src/shared/lib/api/client-fetcher/client-fetcher.ts
  src/shared/lib/api/client-fetcher/client-reissue.ts
  src/shared/lib/api/server-fetcher/server-fetcher.ts
Labels: feat, FE

#235 FE: PR (fix) v2 배포 오류 테스트
  src/app/(with-layout)/(with-header)/challenge/group/feed/FeedPage.tsx
  src/entities/member/context/OAuthUserStore.ts
  src/features/challenge/components/challenge/group/create/DetailStep.tsx
  src/features/challenge/components/challenge/participate/GroupVerificationPage.tsx
  src/features/challenge/components/challenge/participate/verification/VerificationCarousel.tsx
  src/features/challenge/components/challenge/participate/verification/details/VerificationDetails.tsx
  src/features/member/components/member/profile/mypage/Mypage.tsx
  src/features/store/components/product/ProductCard.tsx
  src/features/store/components/time-deal/OngoingTimeDealCard.tsx
  src/features/store/components/time-deal/OngoingTimeDealList.tsx
  src/features/store/components/time-deal/TimeDealList.tsx
  src/features/store/components/time-deal/UpcomingTimeDealList.tsx
  src/shared/components/loading/index.tsx
Labels: bug, FE

#237 FE: PR (feat) 개인 챌린지 인증 제출 롱폴링 전역 수행 로직 구현
  src/app/(with-layout)/(with-header)/challenge/personal/[id]/ChallengePersonalDetails.tsx
  src/app/(with-layout)/layout.tsx
  src/features/challenge/api/get-personal-challenge-details.ts
  src/features/challenge/api/verify-personal-challenge.ts
  src/features/challenge/hook/use-personal-verification-result.ts
  src/shared/components/modal/camera-modal/CameraModal.tsx
  src/shared/config/providers/PollingWatcher.tsx
  src/shared/config/providers/QueryClientProvider.tsx
  src/shared/context/polling/PollingStore.ts
Labels: feat, FE

#240 FE: PR (feat) 단체 챌린지 인증 제출 롱폴링 전역 수행 로직 구현
  src/app/(with-layout)/(with-header)/challenge/personal/[id]/ChallengePersonalDetails.tsx
  src/features/challenge/components/challenge/participate/GroupVerificationPage.tsx
  src/features/challenge/hook/use-group-verification-result.ts
  src/features/challenge/hook/useGroupVerification.ts
  src/shared/config/providers/PollingWatcher.tsx
  src/shared/context/polling/PollingStore.ts
Labels: feat, FE

#253 PR:[feat] 피드백 롱폴링 전역 상태로 관리
  src/entities/member/api/profile/feedback/poll-feedback.ts
  src/features/common/components/polling-watcher/polling-watcher.tsx
  src/features/member/api/index.ts
  src/features/member/api/use-poll-member-feedback.ts
  src/widgets/member/profile/mypage/member-profile-mypage.tsx
Labels: feat

#256 PR:[fix] 인증 상세 자체 qa 적용
  src/app/(with-layout)/(with-header)/challenge/group/[id]/verification/[verificationId]/page.tsx
  src/entities/challenge/api/group/verification/comments/create-comment-reply.ts
  src/entities/challenge/api/group/verification/comments/get-comment-list.ts
  src/features/challenge/components/verification-comment-item/verification-comment-item.tsx
  src/features/challenge/components/verification-comment-list/verification-comment-list.tsx
  src/widgets/challenge/group/[id]/verification/details/challenge-group-verification-details.tsx
Labels: feat, FE

#178 PR:[feat] 챗봇 구조 리팩토링
  .vscode/settings.json
  src/entities/chatbot/api/chatbot-base-info.ts
  src/entities/chatbot/api/index.ts
  src/entities/chatbot/model/constants.ts
  src/entities/chatbot/model/index.ts
  src/entities/chatbot/model/type.ts
  src/entities/chatbot/model/utils.ts
  src/features/chatbot/api/index.ts
  src/features/chatbot/api/use-chat-history.ts
  src/features/chatbot/components/chat-bubble/chat-bubble.tsx
  src/features/chatbot/components/chat-frame/chat-frame.tsx
  src/features/chatbot/components/chat-selection/chat-selection.tsx
  src/shared/components/chatbot/format-response/formatChallengeResponse.tsx
  src/shared/components/chatbot/format-response/index.ts
  src/shared/components/chatbot/horizontal-card/horizontal-card.tsx
  src/shared/components/chatbot/horizontal-card/index.ts
  src/shared/components/chatbot/index.ts
Labels: refactor, FE

#262 fix: FSD 순환참조 에러
  src/features/challenge/components/form-metadata-step/form-metadata-step.tsx
  src/shared/components/index.ts
Labels: bug, FE

#267 feat: 점검중 페이지 배포환경 파일 체킹으로 변경
  src/middleware.ts
Labels: FE, CL

#270 fix: 클립보드 복사 시 라우팅 되는 오류 해결
  src/features/challenge/components/verification-card/verification-card.tsx
Labels: bug, FE

#275 fix: 서비스 시간 점검 데브에서는 삭제
  src/middleware.ts
Labels: bug, FE

#287 PR:[feat] 환경 별 이미지 허용 pathname 할당
  .github/workflows/fe-cicd.yml
  next.config.ts
Labels: feat, FE

#298 PR:[feat] v2 leafresh QA, 에러 수정
  src/features/challenge/api/group/verification/use-create-group-verification.ts
  src/features/challenge/components/verification-carousel/verification-carousel.tsx
  src/features/challenge/components/verification-status-card/verification-status-card.tsx
  src/features/common/components/polling-watcher/polling-watcher.tsx
  src/middleware.ts
  src/shared/components/modal/camera-modal/camera-modal.tsx
  src/widgets/member/challenge/verification/status/member-challenge-verification-status.tsx
Labels: FE
