Repository 100-hours-a-week/15-Leafresh-FE, pull requests merged in 2025-05, with the labels that each got.

#31 FE: PR(Feat) ImageZoomModal Component
  package.json
  pnpm-lock.yaml
  public/file.svg
  public/globe.svg
  public/next.svg
  public/vercel.svg
  public/window.svg
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/entities/challenge/api.ts
  src/entities/challenge/constant.ts
  src/entities/challenge/type.ts
  src/shared/components/zoommodal/ImageZoomModal/ImageZoomModal.tsx
  src/shared/components/zoommodal/ImageZoomModal/ZoomableImage.tsx
  src/shared/constants/endpoint/endpoint.test.ts
  src/shared/context/ZoomModalStore/ImageZoomStore.ts
  src/shared/context/ZoomModalStore/type.ts
  src/shared/hooks/useKeyClose/useKeyClose.ts
  src/shared/lib/api/fetcher/fetcher.test.ts
Labels: feat, FE

#36 FE: PR(Feat) ConfirmModal / useScrollLock ( + style Themes, LucideIcon )
  .github/pull_request_template.md
  package.json
  pnpm-lock.yaml
  src/app/(with-header)/challenge/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/shared/components/ImageInput.tsx
  src/shared/components/Modal/ConfirmModal.tsx
  src/shared/components/zoommodal/ImageZoomModal/ImageZoomModal.tsx
  src/shared/context/Modal/ConfirmModalStore.ts
  src/shared/hooks/useOutsideClick/useOutsideClick.ts
  src/shared/hooks/useScrollLock/useScrollLock.ts
  src/shared/lib/ui/LucideIcon.tsx
  src/shared/styles/emotion.d.ts
  src/shared/styles/theme.ts
  src/shared/styles/type.ts
  src/shared/styles/utitls.ts
Labels: feat, FE

#39 FE: PR(Feat) Dropdown Component Implementation
  package.json
  pnpm-lock.yaml
  src/app/(with-header)/challenge/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/entities/challenge/constant.ts
  src/shared/components/ImageInput.tsx
  src/shared/components/Modal/ConfirmModal.tsx
  src/shared/components/calender/calender-dates.tsx
  src/shared/components/calender/calender-header.tsx
  src/shared/components/calender/calender-weekdays.tsx
  src/shared/components/calender/index.tsx
  src/shared/components/datepicker/DatePicker.tsx
  src/shared/components/dropdown/index.tsx
  src/shared/components/zoommodal/ImageZoomModal/ImageZoomModal.tsx
  src/shared/config/providers/EmotionCacheProvider.tsx
  src/shared/config/providers/Providers.tsx
  src/shared/constants/endpoint/endpoint.ts
  src/shared/lib/date/utils.ts
  src/shared/lib/ui/LucideIcon.tsx
  src/shared/styles/emotion/emotion-cache.ts
  src/shared/styles/emotion/emotion.d.ts
  src/shared/styles/emotion/theme/emotion.d.ts
  src/shared/styles/emotion/theme/index.ts
  src/shared/styles/emotion/theme/type.ts
  src/shared/styles/emotion/theme/utils.ts
  src/shared/styles/emotion/utils.ts
  src/shared/styles/scrollbar/GlobalScrollbarStyle.tsx
Labels: feat, FE

#44 FE: [feat] InfoModal component Inplementation
  src/app/layout.tsx
  src/shared/components/Modal/InfoModal.tsx
  src/shared/context/Modal/InfoModalStore.ts
Labels: feat

#45 FE: PR(Feat) Tanstack Query 기초 설정
  public/font/PretendardVariable.woff2
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/entities/challenge/api.ts
  src/entities/challenge/constant.ts
  src/entities/challenge/type.ts
  src/entities/member/constant.ts
  src/entities/member/type.ts
  src/shared/config/font/index.ts
  src/shared/config/providers/Providers.tsx
  src/shared/config/providers/QueryClientProvider.tsx
  src/shared/config/tanstack-query/queryClient.ts
  src/shared/constants/endpoint/endpoint.ts
  src/shared/constants/tanstack-query/mutation-keys.ts
  src/shared/constants/tanstack-query/query-keys.ts
  src/shared/styles/emotion/theme/index.ts
Labels: feat, FE

#55 FE: PR(Feat) Input Component Implementation
  package.json
  pnpm-lock.yaml
  src/app/(with-header)/store/page.tsx
  src/shared/components/dropdown/index.tsx
  src/shared/components/errortext/index.tsx
  src/shared/components/input/index.tsx
Labels: feat, FE

#51 FE: PR[feat] GridBox Implementation
  src/shared/components/Wrapper/GridBox.tsx
  src/shared/config/providers/ChakraProvider.tsx
  src/shared/config/providers/Providers.tsx
Labels: FE

#58 FE: PR SwitchTap Implementation
  src/app/(with-header)/challenge/page.tsx
  src/app/page.tsx
  src/shared/components/Toast/Toast.tsx
  src/shared/components/switchtap/SwitchTap.tsx
  src/shared/components/zoommodal/ImageZoomModal/ImageZoomModal.tsx
  src/shared/components/zoommodal/ImageZoomModal/ZoomableImage.tsx
Labels: feat, FE

#56 FE: [feat] TimePicker Implementation
  package.json
  pnpm-lock.yaml
  src/app/(with-header)/challenge/page.tsx
  src/shared/components/timepicker/TimeDropdown.tsx
  src/shared/components/timepicker/TimePicker.tsx
Labels: feat, FE

#67 feat: dev 환경 https 설정
  package.json
Labels: feat, FE

#70 FE: feat useImageUpload Implementation
  next.config.ts
  src/features/member/api/signup.ts
  src/shared/components/Toast/Toast.tsx
  src/shared/components/switchtap/SwitchTap.tsx
  src/shared/components/timepicker/TimeDropdown.tsx
  src/shared/constants/endpoint/endpoint.ts
  src/shared/hooks/useImageUpload/useImageUpload.ts
Labels: feat, FE

#72 FE: PR(feat) 챌린지 상세 (단체, 개인)
  next.config.ts
  src/app/(with-header)/challenge/group/[id]/page.tsx
  src/app/(with-header)/challenge/group/create/page.tsx
  src/app/(with-header)/challenge/page.tsx
  src/app/(with-header)/challenge/personal/[id]/page.tsx
  src/app/(with-header)/member/signup/page.tsx
  src/app/(with-header)/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/entities/challenge/constant.ts
  src/entities/challenge/type.ts
  src/features/challenge/api/get-group-challenge-categories.ts
  src/features/challenge/api/get-group-challenge-details.ts
  src/features/challenge/api/get-group-challenge-rules.ts
  src/features/challenge/api/get-personal-challenge-details.ts
  src/features/challenge/api/get-personal-challenge-rules.ts
  src/features/challenge/api/participate-group-challenge.ts
  src/features/challenge/api/verify-personal-challenge.ts
  src/features/challenge/components/challenge/ChallengeMainPage.tsx
  src/features/challenge/components/challenge/group/create/DetailStep.tsx
  src/features/challenge/components/challenge/group/create/MetadataStep.tsx
  src/features/challenge/components/challenge/group/details/ChallengeGroupDetails.tsx
  src/features/challenge/components/challenge/group/details/ChallengeVerifyCarousel.tsx
  src/features/challenge/components/challenge/personal/details/ChallengePersonalDetails.tsx
  src/features/challenge/components/common/ChallengeVerifyExamples.tsx
  src/features/challenge/components/common/VerificationImageInput.tsx
  src/shared/components/Button/BackButton.tsx
  src/shared/components/Modal/camera-modal/CameraModal.tsx
  src/shared/components/Modal/camera-modal/VerificationGuideModal.tsx
  src/shared/components/Toast/Toast.tsx
  src/shared/components/datepicker/DatePicker.tsx
  src/shared/components/header/index.tsx
  src/shared/components/image-input/index.tsx
  src/shared/components/switchtap/SwitchTap.tsx
  src/shared/components/timepicker/TimeDropdown.tsx
  src/shared/components/timepicker/TimePicker.tsx
  src/shared/components/zoommodal/ImageZoomModal/ImageZoomModal.tsx
  src/shared/context/Modal/CameraModalStore.ts
  src/shared/lib/ui/LucideIcon.tsx
  src/shared/types/date.ts
Labels: feat, FE

#73 PR: FE) MVP 페이지(챗봇, 참여 중 챌린지 목록, 참여 중 챌린지 인증 목록, 단체 챌린지 카테고리별 목록)
  public/image/Main2.png
  public/image/Main_Challenge1.png
  public/image/Main_Challenge2.png
  public/image/Main_Challenge3.png
  public/image/Tree_Lv5.png
  public/image/banner_list.jpg
  public/image/chatbot.png
  public/image/chatbotcategory.png
  public/image/chatbotlive.png
  public/image/chatbotwork.png
  src/app/(with-header)/challenge/group/list/page.tsx
  src/app/(with-header)/challenge/group/page.tsx
  src/app/(with-header)/challenge/participate/[participateId]/page.tsx
  src/app/(with-header)/challenge/participate/page.tsx
  src/app/(with-header)/page.tsx
  src/app/layout.tsx
  src/features/challenge/api/get-group-challenge-list.ts
  src/features/challenge/api/participate/group-participant-count.ts
  src/features/challenge/api/participate/group-participant.ts
  src/features/challenge/api/participate/verification/group-verification-list.ts
  src/features/challenge/api/participate/verification/group-verification.ts
  src/features/challenge/components/challenge/group/list/ChallengeListPage.tsx
  src/features/challenge/components/challenge/group/list/GroupChallengeCard.tsx
  src/features/challenge/components/challenge/participate/ChallengeParticipatePage.tsx
  src/features/challenge/components/challenge/participate/GroupChallengeParticipantCard.tsx
  src/features/challenge/components/challenge/participate/GroupChallengeParticipantCardList.tsx
  src/features/challenge/components/challenge/participate/GroupVerificationPage.tsx
  src/features/challenge/components/challenge/participate/verification/VerificationCard.tsx
  src/features/challenge/components/challenge/participate/verification/VerificationCarousel.tsx
  src/features/challenge/hook/useGroupChallengeList.ts
  src/features/challenge/hook/useGroupParticipationsCount.ts
  src/features/challenge/hook/useGroupVerification.ts
  src/features/challenge/hook/useGroupVerificationList.ts
  src/features/challenge/hook/useInfiniteGroupParticipations.ts
  src/features/chatbot/chatbot-base-info.ts
  src/features/chatbot/chatbot-free-text.ts
  src/features/chatbot/index.ts
  src/features/main/ChallengeImageSlider.tsx
  src/features/main/HomePage.tsx
  src/shared/components/Modal/camera-modal/CameraModal.tsx
  src/shared/components/chatbot/ChatBubble.tsx
  src/shared/components/chatbot/ChatFrame.tsx
  src/shared/components/chatbot/ChatHeader.tsx
  src/shared/components/chatbot/ChatSelection.tsx
  src/shared/components/chatbot/ChatWindow.tsx
  src/shared/components/chatbot/Chatbot.tsx
  src/shared/components/slidearea/SlideArea.tsx
Labels: feat, FE

#75 FE: PR(Feat) MVP 릴리즈 QA 사항
  eslint.config.mjs
  next.config.ts
  package-lock.json
  package.json
  src/app/(with-header)/challenge/group/[id]/page.tsx
  src/app/(with-header)/challenge/group/create/page.tsx
  src/app/(with-header)/challenge/group/list/page.tsx
  src/app/(with-header)/challenge/participate/[participateId]/page.tsx
  src/app/(with-header)/challenge/personal/[id]/page.tsx
  src/app/(with-header)/member/login/page.tsx
  src/app/(with-header)/member/signup/page.tsx
  src/app/(with-header)/oauth/[provider]/callback/page.tsx
  src/app/(with-header)/page.tsx
  src/app/layout.tsx
  src/features/challenge/api/get-group-challenge-list.ts
  src/features/challenge/api/participate/group-participant-count.ts
  src/features/challenge/api/participate/group-participant.ts
  src/features/challenge/api/participate/verification/group-verification-list.ts
  src/features/challenge/api/participate/verification/group-verification.ts
  src/features/challenge/components/challenge/ChallengeMainPage.tsx
  src/features/challenge/components/challenge/group/create/MetadataStep.tsx
  src/features/challenge/components/challenge/group/list/ChallengeListPage.tsx
  src/features/challenge/components/challenge/group/list/GroupChallengeCard.tsx
  src/features/challenge/components/challenge/participate/ChallengeParticipatePage.tsx
  src/features/challenge/components/challenge/participate/GroupChallengeParticipantCard.tsx
  src/features/challenge/components/challenge/participate/GroupVerificationPage.tsx
  src/features/challenge/components/challenge/participate/verification/VerificationCard.tsx
  src/features/challenge/components/challenge/participate/verification/VerificationCarousel.tsx
  src/features/challenge/hook/useGroupChallengeList.ts
  src/features/challenge/hook/useGroupParticipationsCount.ts
  src/features/challenge/hook/useGroupVerification.ts
  src/features/challenge/hook/useGroupVerificationList.ts
  src/features/challenge/hook/useInfiniteGroupParticipations.ts
  src/features/chatbot/chatbot-base-info.ts
  src/features/chatbot/chatbot-free-text.ts
  src/features/chatbot/index.ts
  src/features/main/ChallengeImageSlider.tsx
  src/features/member/api/logout.ts
  src/features/member/api/unregister.ts
  src/features/member/signup/schema.ts
  src/shared/components/Toast/Toast.tsx
  src/shared/components/chatbot/ChatBubble.tsx
  src/shared/components/chatbot/ChatFrame.tsx
  src/shared/components/chatbot/ChatHeader.tsx
  src/shared/components/chatbot/ChatSelection.tsx
  src/shared/components/chatbot/ChatWindow.tsx
  src/shared/components/chatbot/Chatbot.tsx
  src/shared/components/header/index.tsx
  src/shared/components/slidearea/SlideArea.tsx
  src/shared/constants/route/route.ts
  src/shared/hooks/useImageUpload/useImageUpload.ts
  src/shared/hooks/useKeyClose/useKeyClose.ts
  src/shared/hooks/useOutsideClick/useOutsideClick.ts
  vitest.config.mts
Labels: test, FE, Emergency

#77 릴리즈 단계 QA
  src/app/(with-header)/challenge/group/[id]/participate/list/page.tsx
  src/app/(with-header)/challenge/group/list/page.tsx
  src/app/(with-header)/fe-oauth/[provider]/login/page.tsx
  src/app/(with-header)/member/alarm/page.tsx
  src/app/(with-header)/member/login/page.tsx
  src/features/challenge/api/get-group-challenge-list.ts
  src/features/challenge/api/get-personal-challenge-list.ts
  src/features/challenge/api/participate/get-group-participant-list.ts
  src/features/challenge/components/challenge/ChallengeMainPage.tsx
  src/features/challenge/components/challenge/group/list/ChallengeListPage.tsx
  src/features/challenge/components/challenge/group/list/GroupChallengeCard.tsx
  src/features/challenge/components/challenge/participate/list/ChallengeGroupParticipateList.tsx
  src/features/challenge/components/challenge/personal/details/ChallengePersonalDetails.tsx
  src/features/challenge/components/member/alarm/MemberAlramList.tsx
  src/features/challenge/hook/useInfiniteGroupChallengeVerifications.ts
  src/features/member/api/get-alarm.ts
  src/features/member/hooks/useInfiniteMemberAlarmList.ts
  src/shared/components/chatbot/Chatbot.tsx
  src/shared/constants/tanstack-query/query-keys.ts
Labels: bug, FE

#82 FE: PR[feat] 쿼리키 무효화 시점 정의 (중앙 집중화)
  src/app/(with-header)/challenge/group/[id]/page.tsx
  src/app/(with-header)/challenge/group/[id]/participate/list/page.tsx
  src/app/(with-header)/challenge/group/create/page.tsx
  src/app/(with-header)/challenge/page.tsx
  src/app/(with-header)/challenge/personal/[id]/page.tsx
  src/app/(with-header)/fe-oauth/[provider]/login/page.tsx
  src/app/(with-header)/member/alarm/page.tsx
  src/app/(with-header)/member/login/page.tsx
  src/app/(with-header)/member/signup/page.tsx
  src/features/challenge/api/create-group-challenge.ts
  src/features/challenge/api/get-group-challenge-list.ts
  src/features/challenge/api/participate-group-challenge.ts
  src/features/challenge/api/participate/verification/group-verification.ts
  src/features/challenge/api/verify-personal-challenge.ts
  src/features/challenge/components/challenge/ChallengeMainPage.tsx
  src/features/challenge/components/challenge/group/details/ChallengeGroupDetails.tsx
  src/features/challenge/components/challenge/group/list/ChallengeListPage.tsx
  src/features/challenge/components/challenge/participate/GroupVerificationPage.tsx
  src/features/challenge/components/challenge/personal/details/ChallengePersonalDetails.tsx
  src/features/challenge/components/member/alarm/MemberAlramList.tsx
  src/features/challenge/hook/useGroupChallengeList.ts
  src/features/challenge/hook/useGroupParticipationsCount.ts
  src/features/challenge/hook/useGroupVerification.ts
  src/features/challenge/hook/useGroupVerificationList.ts
  src/features/challenge/hook/useInfiniteGroupChallengeVerifications.ts
  src/features/challenge/hook/useInfiniteGroupParticipations.ts
  src/features/member/api/logout.ts
  src/features/member/api/read-all-alarms.ts
  src/features/member/api/signup.ts
  src/features/member/api/unregister.ts
  src/features/member/hooks/useInfiniteMemberAlarmList.ts
  src/shared/components/Modal/camera-modal/CameraModal.tsx
  src/shared/components/Modal/camera-modal/VerificationGuideModal.tsx
  src/shared/components/header/index.tsx
  src/shared/config/tanstack-query/mutation-defaults.ts
  src/shared/config/tanstack-query/mutation-keys.ts
  src/shared/config/tanstack-query/query-defaults.ts
  src/shared/config/tanstack-query/query-keys.ts
  src/shared/config/tanstack-query/queryClient.ts
  src/shared/constants/endpoint/endpoint.ts
  src/shared/constants/tanstack-query/mutation-keys.ts
Labels: feat, FE

#85 FE: PR(bug) QA를 통해 발견한 오류 해결
  next.config.ts
  src/app/(with-header)/challenge/group/create/page.tsx
  src/app/(with-header)/fe-oauth/[provider]/login/page.tsx
  src/app/(with-header)/layout.tsx
  src/app/(with-header)/member/login/page.tsx
  src/app/(with-header)/member/signup/page.tsx
  src/app/layout.tsx
  src/entities/member/context/OAuthUserStore.ts
  src/features/challenge/api/participate/get-group-participant-list.ts
  src/features/challenge/components/challenge/ChallengeMainPage.tsx
  src/features/challenge/components/challenge/group/create/DetailStep.tsx
  src/features/challenge/components/challenge/group/create/MetadataStep.tsx
  src/features/challenge/components/challenge/group/details/ChallengeGroupDetails.tsx
  src/features/challenge/components/challenge/group/details/ChallengeVerifyCarousel.tsx
  src/features/challenge/components/challenge/group/list/ChallengeListPage.tsx
  src/features/challenge/components/challenge/group/list/GroupChallengeCard.tsx
  src/features/challenge/components/challenge/participate/ChallengeParticipatePage.tsx
  src/features/challenge/components/challenge/participate/GroupChallengeParticipantCard.tsx
  src/features/challenge/components/challenge/participate/GroupVerificationPage.tsx
  src/features/challenge/components/challenge/participate/list/ChallengeGroupParticipateList.tsx
  src/features/challenge/components/challenge/participate/verification/VerificationCarousel.tsx
  src/features/challenge/components/challenge/personal/details/ChallengePersonalDetails.tsx
  src/features/challenge/components/common/VerificationImageInput.tsx
  src/features/challenge/components/member/alarm/MemberAlramList.tsx
  src/features/main/ChallengeImageSlider.tsx
  src/features/member/api/logout.ts
  src/features/member/api/signup.ts
  src/features/member/api/unregister.ts
  src/shared/components/Modal/ConfirmModal.tsx
  src/shared/components/Modal/ModalProvider.tsx
  src/shared/components/Modal/camera-modal/CameraModal.tsx
  src/shared/components/Modal/camera-modal/VerificationGuideModal.tsx
  src/shared/components/Toast/Toast.tsx
  src/shared/components/chatbot/Chatbot.tsx
  src/shared/components/header/index.tsx
  src/shared/components/slide-drawer/SlideDrawer.tsx
  src/shared/components/timepicker/TimeDropdown.tsx
  src/shared/components/zoommodal/ImageZoomModal/ImageZoomModal.tsx
  src/shared/config/tanstack-query/mutation-defaults.ts
  src/shared/context/back-button/BackButtonStore.ts
  src/shared/context/slide-drawer/DrawerStore.ts
  src/shared/hooks/useScrollLock/useScrollLock.ts
  src/shared/lib/api/fetcher/fetcher.ts
  src/shared/styles/GlobalStyle.tsx
  src/shared/styles/LayoutWrapper.tsx
Labels: feat, bug, FE

#88 PR: [fix] QA 수정
  src/features/challenge/api/get-event-challenge-list.ts
  src/features/challenge/components/challenge/ChallengeMainPage.tsx
  src/features/challenge/components/challenge/group/list/ChallengeListPage.tsx
  src/features/challenge/components/challenge/participate/GroupVerificationPage.tsx
  src/shared/components/Modal/ConfirmModal.tsx
  src/shared/components/Modal/camera-modal/CameraModal.tsx
  src/shared/components/chatbot/ChatBubble.tsx
  src/shared/components/chatbot/ChatFrame.tsx
  src/shared/components/chatbot/ChatSelection.tsx
  src/shared/components/chatbot/Chatbot.tsx
  src/shared/components/slide-drawer/SlideDrawer.tsx
Labels: bug, FE

#92 feat: favicon
  middleware.ts
  next.config.ts
  public/icon/favicon.ico
  src/app/layout.tsx
Labels: feat, FE

#91 PR [fix] 카메라 모달 전후면 전환 및 사용 에러 핸들링
  src/app/layout.tsx
  src/shared/components/Modal/camera-modal/CameraModal.tsx
Labels: bug, FE

#94 FE: PR(Feat) 단체 챌린지 카테고리 목록 조회 API 정적 이미지 연동
  public/icon/category_book_share.png
  public/icon/category_carbon_reduction.png
  public/icon/category_digital_carbon.png
  public/icon/category_energy_saving.png
  public/icon/category_plogging.png
  public/icon/category_upcycle.png
  public/icon/category_vegan.png
  public/icon/category_zero_waste.png
  src/app/layout.tsx
  src/entities/challenge/constant.ts
  src/features/challenge/components/challenge/ChallengeMainPage.tsx
Labels: feat, FE

#117 FE: PR(chore) 단체 챌린지 기타 카테고리 삭제
  src/features/challenge/components/challenge/ChallengeMainPage.tsx
  src/features/challenge/components/challenge/group/create/MetadataStep.tsx
Labels: chore, FE

#110 FE: PR(refactor) fetchReqeust + useMutationStore 반환 타입 최적화
  src/features/challenge/api/create-group-challenge.ts
  src/features/challenge/api/get-event-challenge-list.ts
  src/features/challenge/api/get-group-challenge-categories.ts
  src/features/challenge/api/get-group-challenge-details.ts
  src/features/challenge/api/get-group-challenge-list.ts
  src/features/challenge/api/get-group-challenge-rules.ts
  src/features/challenge/api/get-personal-challenge-details.ts
  src/features/challenge/api/get-personal-challenge-list.ts
  src/features/challenge/api/get-personal-challenge-rules.ts
  src/features/challenge/api/participate-group-challenge.ts
  src/features/challenge/api/participate/get-group-participant-list.ts
  src/features/challenge/api/participate/group-participant-count.ts
  src/features/challenge/api/participate/group-participant.ts
  src/features/challenge/api/participate/verification/group-verification-list.ts
  src/features/challenge/api/participate/verification/group-verification.ts
  src/features/challenge/api/verify-personal-challenge.ts
  src/features/challenge/components/challenge/group/list/ChallengeListPage.tsx
  src/features/challenge/components/challenge/participate/ChallengeParticipatePage.tsx
  src/features/challenge/hook/useGroupChallengeList.ts
  src/features/challenge/hook/useGroupParticipationsCount.ts
  src/features/challenge/hook/useGroupVerification.ts
  src/features/challenge/hook/useGroupVerificationList.ts
  src/features/challenge/hook/useInfiniteGroupParticipations.ts
  src/features/chatbot/chatbot-base-info.ts
  src/features/chatbot/chatbot-free-text.ts
  src/features/member/api/get-alarm.ts
  src/features/member/api/logout.ts
  src/features/member/api/nickname-duplicate.ts
  src/features/member/api/oauth-callback.ts
  src/features/member/api/oauth-login.ts
  src/features/member/api/read-all-alarms.ts
  src/features/member/api/signup.ts
  src/features/member/api/unregister.ts
  src/shared/config/tanstack-query/mutation-defaults.ts
  src/shared/hooks/useImageUpload/useImageUpload.ts
  src/shared/lib/api/fetcher/fetcher.ts
  src/shared/types/api.ts
Labels: refactor, FE

#97 PR:[refactor] 챗봇 api
  src/features/chatbot/chatbot-base-info.ts
  src/features/chatbot/chatbot-free-text.ts
  src/shared/components/chatbot/ChatFrame.tsx
  src/shared/components/chatbot/ChatSelection.tsx
Labels: refactor, FE

#126 FE: PR(fix) 기타 챌린지 카테고리 삭제 및 카테고리명 변경
  src/entities/challenge/constant.ts
  src/features/challenge/components/challenge/ChallengeMainPage.tsx
Labels: feat, FE

#129 FE: PR(style) "챌린지 목록" 이벤트 챌린지 캐러셀 추가 + 생성한 단체 챌린지 폰트 키우기
  src/entities/challenge/constant.ts
  src/features/challenge/components/challenge/ChallengeMainPage.tsx
  src/features/member/components/challenge/creations/MemberChallengeCreationsPage.tsx
Labels: style, FE

#138 Create LICENSE
  LICENSE
Labels: docs, FE

#141 PR: 1차 배포 QA 에러 핸들링
  public/image/challenge/carbon_banner.png
  public/image/challenge/foot_banner.png
  public/image/challenge/media_banner.png
  public/image/challenge/plogging_banner.png
  public/image/challenge/saving_banner.png
  public/image/challenge/upcycle_banner.png
  public/image/challenge/vegan_banner.png
  public/image/challenge/zero_banner.png
  public/image/chatbot/athome.jpg
  public/image/chatbot/beach.jpg
  public/image/chatbot/business.jpg
  public/image/chatbot/chatbot.png
  public/image/chatbot/chatbot_bubble.png
  public/image/chatbot/chatbotcategory.png
  public/image/chatbot/city.jpg
  public/image/chatbot/farm.jpg
  public/image/chatbot/fieldwork.jpg
  public/image/chatbot/mountain.jpg
  public/image/chatbot/sales.jpg
  public/image/chatbotcategory.png
  public/image/main-icon.svg
  src/features/challenge/components/challenge/group/list/ChallengeListPage.tsx
  src/features/main/ChallengeImageSlider.tsx
  src/features/main/hook/useScrollTrigger.ts
  src/shared/components/chatbot/ChatBubble.tsx
  src/shared/components/chatbot/ChatFrame.tsx
  src/shared/components/chatbot/ChatSelection.tsx
  src/shared/components/chatbot/ChatWindow.tsx
  src/shared/components/chatbot/Chatbot.tsx
  src/shared/components/slidearea/SlideArea.tsx
  src/shared/components/timepicker/TimeDropdown.tsx
Labels: bug, FE

#140 FE: PR(fix) 스프린트4 QA 반영 목록 + SSR 쿠키 담기 요청 추가
  src/app/(with-header)/challenge/ChallengeMainPage.tsx
  src/app/(with-header)/challenge/group/create/GroupChallengeCreatePage.tsx
  src/app/(with-header)/challenge/group/create/page.tsx
  src/app/(with-header)/challenge/page.tsx
  src/app/(with-header)/challenge/personal/[id]/ChallengePersonalDetails.tsx
  src/app/(with-header)/challenge/personal/[id]/page.tsx
  src/features/challenge/api/get-personal-challenge-details.ts
  src/features/challenge/components/challenge/group/create/DetailStep.tsx
  src/features/challenge/components/challenge/group/create/MetadataStep.tsx
  src/features/challenge/components/challenge/group/details/ChallengeGroupDetails.tsx
  src/features/challenge/components/common/ChallengeVerifyExamples.tsx
  src/features/challenge/hook/useGroupChallengeList.ts
  src/features/challenge/hook/useGroupVerification.ts
  src/features/challenge/hook/useInfiniteGroupChallengeVerifications.ts
  src/features/challenge/hook/useInfiniteGroupParticipations.ts
  src/features/member/hooks/useInfiniteMemberAlarmList.ts
  src/features/member/hooks/useInfiniteMemberChallengeCreationsList.ts
  src/shared/components/Modal/camera-modal/CameraModal.tsx
  src/shared/components/Toast/Toast.tsx
  src/shared/config/tanstack-query/mutation-defaults.ts
  src/shared/config/tanstack-query/queryClient.ts
  src/shared/lib/api/fetcher/fetcher.test.ts
  src/shared/lib/api/fetcher/fetcher.ts
  src/shared/lib/api/fetcher/index.ts
  src/shared/lib/api/fetcher/serverFetchRequest.ts
  src/shared/lib/api/fetcher/type.ts
Labels: feat, bug, FE

#144 FE: PR(fix) QA 핸들링
  src/app/(with-header)/challenge/ChallengeMainPage.tsx
  src/app/(with-header)/challenge/page.tsx
  src/app/(with-header)/challenge/personal/[id]/ChallengePersonalDetails.tsx
  src/app/(with-header)/challenge/personal/[id]/page.tsx
  src/features/challenge/api/get-personal-challenge-details.ts
  src/features/challenge/components/challenge/group/GroupChallengeFormPage.tsx
  src/features/challenge/components/challenge/group/create/DetailStep.tsx
  src/features/challenge/components/challenge/group/create/MetadataStep.tsx
  src/features/challenge/components/challenge/group/details/ChallengeGroupDetails.tsx
  src/features/challenge/components/common/ChallengeVerifyExamples.tsx
  src/features/challenge/hook/useGroupChallengeList.ts
  src/features/challenge/hook/useGroupVerification.ts
  src/features/challenge/hook/useInfiniteGroupChallengeVerifications.ts
  src/features/challenge/hook/useInfiniteGroupParticipations.ts
  src/features/member/hooks/useInfiniteMemberAlarmList.ts
  src/features/member/hooks/useInfiniteMemberChallengeCreationsList.ts
  src/shared/components/Modal/camera-modal/CameraModal.tsx
  src/shared/components/Toast/Toast.tsx
  src/shared/config/tanstack-query/mutation-defaults.ts
  src/shared/config/tanstack-query/queryClient.ts
  src/shared/lib/api/fetcher/fetcher.test.ts
  src/shared/lib/api/fetcher/fetcher.ts
  src/shared/lib/api/fetcher/index.ts
  src/shared/lib/api/fetcher/serverFetchRequest.ts
  src/shared/lib/api/fetcher/type.ts
Labels: bug, FE

#149 Hotfix/v1.0.4
  src/app/layout.tsx
  src/features/challenge/components/challenge/group/list/ChallengeListPage.tsx
  src/shared/components/Toasing-test/Toast.tsx
  src/shared/components/Wrapping-test/GridBox.tsx
  src/shared/components/modal/ConfirmModal.tsx
  src/shared/components/modal/InfoModal.tsx
  src/shared/components/modal/ModalProvider.tsx
  src/shared/components/modal/camera-modal/CameraModal.tsx
  src/shared/components/modal/camera-modal/VerificationGuideModal.tsx
Labels: FE, Emergency

#157 v1.0.5 / Playwright 설치
  .gitignore
  package.json
  playwright.config.ts
  pnpm-lock.yaml
  tests-examples/demo-todo-app.spec.ts
  tests/example.spec.ts
Labels: FE, Emergency

#158 chore: 테스트 명령어 생성 (pnpm test:e2e)
  package.json
Labels: FE

#164 FE: (PR) 특정 카테고리 챌린지 추출 오류
  src/features/challenge/components/challenge/group/list/ChallengeListPage.tsx
  src/features/challenge/hook/useGroupChallengeList.ts
Labels: FE, Emergency
